sudo: false

language: java
jdk: oraclejdk7

env:
  global:
    - secure: "FUV1hPOEUWCQ5vLNQOxZwB6EaNGmWymEA3EHJ/FjPJjz0GTt8NqvrwNakfCYlFAF9+ifZ60J1CC+R0u74GnAj1Ae0kVOtyduYTPTBazQX7Jcr6lsxp5EOzkuVaRVySLs5fgOrVxYv7Isv2PimEkMF3dZEh7vHdhvBvSR9H9ZKDw="
    - COVERITY_SCAN_PROJECT_NAME: dresden-ocl/dresdenocl

cache:
  directories:
    - $HOME/.m2
addons:
  ssh_known_hosts: lars.inf.tu-dresden.de
  coverity_scan:
    project:
      name: dresden-ocl/dresdenocl
      version: 3.4.0
    notification_email: dev@larsschuetze.de
    build_command_prepend: cov-configure --java
    build_command: mvn install -Dmaven.test.skip=true -DskipTests -B
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2003f73d9ccfbf9e3e53
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always

before_script:
  - export MAVEN_OPTS="-Xms1024m -Xmx3072m -XX:PermSize=512m"

install: /bin/true

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mvn install -Dmaven.javadoc.skip=true -Dtycho.disableP2Mirrors=true -B -V ; fi
  #- if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mvn install -DskipTests -Dmaven.javadoc.skip=true -Dtycho.disableP2Mirrors=true -B -V ; fi
  #- if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mvn verify -e --file tests/pom.xml -Dtycho.showEclipseLog=true ; fi
  #- if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mvn cobertura:cobertura coveralls:report ; fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn install -Dmaven.test.skip=true -DskipTests -Dtycho.disableP2Mirrors=true -B -P latest-luna ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn install -Dmaven.test.skip=true -DskipTests -Dtycho.disableP2Mirrors=true -B -P release-luna ; fi
