# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk: openjdk6

cache:
  directories:
    - '$HOME/.m2/repository'

git:
  depth: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2003f73d9ccfbf9e3e53
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

before_script:
  #- echo -e "Host lars.inf.tu-dresden.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: /bin/true
script:
  - mvn clean install -B 
  #- mvn clean cobertura:cobertura coveralls:report
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn install -Dmaven.test.skip=true -B -P upload-latest ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn install -Dmaven.test.skip=true -B -P upload-release ; fi
