# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk: openjdk6

cache:
  directories:
    - '$HOME/.m2/repository'

install: /bin/true
script:
  - mvn clean install integration-test -B 
  #- mvn clean cobertura:cobertura coveralls:report
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop"] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn deploy -B -P upload-latest ; fi
  - if [ "$TRAVIS_BRANCH" == "master"] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn deploy -B -P upload-release ; fi
